// utils/options.js
export const languageOptions = [
    { value: "English", label: "🇬🇧 English" },
    { value: "French", label: "🇫🇷 French" },
    { value: "German", label: "🇩🇪 German" },
    { value: "Italian", label: "🇮🇹 Italian" },
    { value: "Spanish", label: "🇪🇸 Spanish" },
    { value: "Chinese", label: "🇨🇳 Chinese" },
    { value: "Japanese", label: "🇯🇵 Japanese" },
    { value: "Korean", label: "🇰🇷 Korean" },
    { value: "Arabic", label: "🇦🇪 Arabic" },
    { value: "Russian", label: "🇷🇺 Russian" },
    { value: "Portuguese", label: "🇵🇹 Portuguese" },
    { value: "Dutch", label: "🇳🇱 Dutch" },
    { value: "Greek", label: "🇬🇷 Greek" },
    { value: "Hindi", label: "🇮🇳 Hindi" },
    { value: "Urdu", label: "🇵🇰 Urdu" },
    { value: "Turkish", label: "🇹🇷 Turkish" },
    { value: "Swedish", label: "🇸🇪 Swedish" },
    { value: "Norwegian", label: "🇳🇴 Norwegian" },
    { value: "Danish", label: "🇩🇰 Danish" },
    { value: "Finnish", label: "🇫🇮 Finnish" },
    { value: "Polish", label: "🇵🇱 Polish" },
    { value: "Czech", label: "🇨🇿 Czech" },
    { value: "Slovak", label: "🇸🇰 Slovak" },
    { value: "Hungarian", label: "🇭🇺 Hungarian" },
    { value: "Romanian", label: "🇷🇴 Romanian" },
    { value: "Bulgarian", label: "🇧🇬 Bulgarian" },
    { value: "Serbian", label: "🇷🇸 Serbian" },
    { value: "Croatian", label: "🇭🇷 Croatian" },
    { value: "Slovenian", label: "🇸🇮 Slovenian" },
    { value: "Albanian", label: "🇦🇱 Albanian" },
    { value: "Macedonian", label: "🇲🇰 Macedonian" },
    { value: "Bosnian", label: "🇧🇦 Bosnian" },
    { value: "Montenegrin", label: "🇲🇪 Montenegrin" },
    { value: "Kosovar", label: "🇽🇰 Kosovar" },
    { value: "Georgian", label: "🇬🇪 Georgian" },
    { value: "Armenian", label: "🇦🇲 Armenian" },
    { value: "Azerbaijani", label: "🇦🇿 Azerbaijani" },
    { value: "Kazakh", label: "🇰🇿 Kazakh" },
    { value: "Uzbek", label: "🇺🇿 Uzbek" },
    { value: "Turkmen", label: "🇹🇲 Turkmen" },
    { value: "Kyrgyz", label: "🇰🇬 Kyrgyz" },
    { value: "Tajik", label: "🇹🇯 Tajik" },
    { value: "Afghan", label: "🇦🇫 Afghan" },
    { value: "Pakistani", label: "🇵🇰 Pakistani" },
    { value: "Indian", label: "🇮🇳 Indian" },
    { value: "Bangladeshi", label: "🇧🇩 Bangladeshi" },
    { value: "Nepali", label: "🇳🇵 Nepali" },
    { value: "Bhutanese", label: "🇧🇹 Bhutanese" },
    { value: "Sri Lankan", label: "🇱🇰 Sri Lankan" },
    { value: "Maldivian", label: "🇲🇻 Maldivian" },
    { value: "American", label: "🇺🇸 American" },
    { value: "Canadian", label: "🇨🇦 Canadian" },
    { value: "Mexican", label: "🇲🇽 Mexican" },
    { value: "Brazilian", label: "🇧🇷 Brazilian" },
    { value: "Argentinian", label: "🇦🇷 Argentinian" },
    { value: "Chilean", label: "🇨🇱 Chilean" },
    { value: "Peruvian", label: "🇵🇪 Peruvian" },
    { value: "Colombian", label: "🇨🇴 Colombian" },
    { value: "Venezuelan", label: "🇻🇪 Venezuelan" },
    { value: "Ecuadorian", label: "🇪🇨 Ecuadorian" },
  // Ajoutez d'autres langues si nécessaire
];


export const cities = [
    { name: "Paris, France", link: "/gigs?country=France&city=Paris" },
    { name: "Barcelone, Spain", link: "/gigs?country=Spain&city=Barcelone" },
    { name: "New York, United States", link: "/gigs?country=United+States&city=New+York" },
    { name: "Rome, Italy", link: "/gigs?country=Italy&city=Rome" },
    { name: "Pékin, China", link: "/gigs?country=China&city=Pékin" },
    { name: "Istanbul, Turkey", link: "/gigs?country=Turkey&city=Istanbul" },
    { name: "Cancún, Mexico", link: "/gigs?country=Mexico&city=Cancún" },
    { name: "Bangkok, Thailand", link: "/gigs?country=Thailand&city=Bangkok" },
    { name: "London, United Kingdom", link: "/gigs?country=United+Kingdom&city=London" },
    { name: "Berlin, Germany", link: "/gigs?country=Germany&city=Berlin" },
    { name: "Tokyo, Japan", link: "/gigs?country=Japan&city=Tokyo" },
    { name: "Vienna, Austria", link: "/gigs?country=Austria&city=Vienna" },
    { name: "Athens, Greece", link: "/gigs?country=Greece&city=Athens" },
    { name: "Moscow, Russia", link: "/gigs?country=Russia&city=Moscow" },
    { name: "Kuala Lumpur, Malaysia", link: "/gigs?country=Malaysia&city=Kuala+Lumpur" },
    { name: "Lisbon, Portugal", link: "/gigs?country=Portugal&city=Lisbon" },
    { name: "Toronto, Canada", link: "/gigs?country=Canada&city=Toronto" },
    { name: "Amsterdam, Netherlands", link: "/gigs?country=Netherlands&city=Amsterdam" },
    { name: "Warsaw, Poland", link: "/gigs?country=Poland&city=Warsaw" },
    { name: "Budapest, Hungary", link: "/gigs?country=Hungary&city=Budapest" },
    { name: "Singapore, Singapore", link: "/gigs?country=Singapore&city=Singapore" },
    { name: "Seoul, South Korea", link: "/gigs?country=South+Korea&city=Seoul" },
    { name: "Jakarta, Indonesia", link: "/gigs?country=Indonesia&city=Jakarta" },
    { name: "Delhi, India", link: "/gigs?country=India&city=Delhi" },
    { name: "Dubrovnik, Croatia", link: "/gigs?country=Croatia&city=Dubrovnik" },
    { name: "Zurich, Switzerland", link: "/gigs?country=Switzerland&city=Zurich" },
    { name: "Mecca, Saudi Arabia", link: "/gigs?country=Saudi+Arabia&city=Mecca" },
    { name: "Brussels, Belgium", link: "/gigs?country=Belgium&city=Brussels" },
    { name: "Dublin, Ireland", link: "/gigs?country=Ireland&city=Dublin" },
    { name: "Hanoi, Vietnam", link: "/gigs?country=Vietnam&city=Hanoi" }
];
export const pointsOfInterestOptions = [
//
    { name: "Business", icon: "./img/icons8-b2b-50.png" },
    { name: "Administration", icon: "./img/icons8-administration.png" },

    //businnes


    { name: "Museum", icon: "https://img.icons8.com/ios/50/000000/museum.png" },
    { name: "Beach", icon: "https://img.icons8.com/ios/50/000000/beach.png" },


    {
        name: "Night Club",
        icon: "https://img.icons8.com/?size=100&id=60357&format=png&color=000000",
    },
    {
        name: "Park",
        icon: "https://img.icons8.com/?size=100&id=7XFQqoCVoosj&format=png&color=000000",
    },
    {
        name: "Shopping Mall",
        icon: "https://img.icons8.com/ios/50/000000/shopping-mall.png",
    },
    {
        name: "Theatre",
        icon: "https://img.icons8.com/?size=100&id=zbPYzShUWkkU&format=png&color=000000",
    },
    {
        name: "Amusement Park",
        icon: "https://img.icons8.com/?size=100&id=25053&format=png&color=000000",
    },
    {
        name: "Restaurant",
        icon: "https://img.icons8.com/ios/50/000000/restaurant.png",
    },
    {
        name: "Hiking",
        icon: "https://img.icons8.com/?size=100&id=9844&format=png&color=000000",
    },
];
export const countriesData = [
    { name: "France", flag: "🇫🇷" },
    { name: "Germany", flag: "🇩🇪" },
    { name: "Italy", flag: "🇮🇹" },
    { name: "Spain", flag: "🇪🇸" },
    { name: "China", flag: "🇨🇳" },
    { name: "Japan", flag: "🇯🇵" },
    { name: "Korea", flag: "🇰🇷" },
    { name: "Arab Emirates", flag: "🇦🇪" },
    { name: "Russia", flag: "🇷🇺" },
    { name: "Portugal", flag: "🇵🇹" },
    { name: "Netherlands", flag: "🇳🇱" },
    { name: "Greece", flag: "🇬🇷" },
    { name: "India", flag: "🇮🇳" },
    { name: "Pakistan", flag: "🇵🇰" },
    { name: "Turkey", flag: "🇹🇷" },
    { name: "Sweden", flag: "🇸🇪" },
    { name: "Norway", flag: "🇳🇴" },
    { name: "Denmark", flag: "🇩🇰" },
    { name: "Finland", flag: "🇫🇮" },
    { name: "Switzerland", flag: "🇨🇭" },
    { name: "Austria", flag: "🇦🇹" },
    { name: "Belgium", flag: "🇧🇪" },
    { name: "Poland", flag: "🇵🇱" },
    { name: "Czech Republic", flag: "🇨🇿" },
    { name: "Hungary", flag: "🇭🇺" },
    { name: "Romania", flag: "🇷🇴" },
    { name: "Bulgaria", flag: "🇧🇬" },
    { name: "Croatia", flag: "🇭🇷" },
    { name: "Serbia", flag: "🇷🇸" },
    { name: "Bosnia and Herzegovina", flag: "🇧🇦" },
    //go
    { name: "United States", flag: "🇺🇸" },
    { name: "Canada", flag: "🇨🇦" },
    { name: "Mexico", flag: "🇲🇽" },
    { name: "Brazil", flag: "🇧🇷" },
    { name: "Argentina", flag: "🇦🇷" },
    { name: "Chile", flag: "🇨🇱" },
    { name: "Colombia", flag: "🇨🇴" },
    { name: "Peru", flag: "🇵🇪" },
    { name: "Venezuela", flag: "🇻🇪" },
    { name: "Ecuador", flag: "🇪🇨" },
    { name: "Uruguay", flag: "🇺🇾" },
    { name: "Paraguay", flag: "🇵🇾" },
    { name: "Bolivia", flag: "🇧🇴" },
    { name: "Australia", flag: "🇦🇺" },
    { name: "New Zealand", flag: "🇳🇿" },
    { name: "Fiji", flag: "🇫🇯" },
    { name: "Papua New Guinea", flag: "🇵🇬" },
    { name: "Solomon Islands", flag: "🇸🇧" },
    { name: "Vanuatu", flag: "🇻🇺" },
    { name: "Samoa", flag: "🇼🇸" },
    { name: "Tonga", flag: "🇹🇴" },
    { name: "Kiribati", flag: "🇰🇮" },
    { name: "Tuvalu", flag: "🇹🇻" },
    { name: "Nauru", flag: "🇳🇷" },
    { name: "Marshall Islands", flag: "🇲🇭" },
    { name: "Micronesia", flag: "🇫🇲" },
    { name: "Palau", flag: "🇵🇼" },
    { name: "Singapore", flag: "🇸🇬" },
    { name: "Malaysia", flag: "🇲🇾" },
    { name: "Indonesia", flag: "🇮🇩" },
    { name: "Philippines", flag: "🇵🇭" },
    { name: "Thailand", flag: "🇹🇭" },
    { name: "Vietnam", flag: "🇻🇳" },
    { name: "Cambodia", flag: "🇰🇭" },
    { name: "Laos", flag: "🇱🇦" },
    { name: "Myanmar", flag: "🇲🇲" },
    { name: "Bangladesh", flag: "🇧🇩" },
    { name: "Nepal", flag: "🇳🇵" },
    { name: "Sri Lanka", flag: "🇱🇰" },
    { name: "Afghanistan", flag: "🇦🇫" },
    { name: "Iran", flag: "🇮🇷" },
    { name: "Iraq", flag: "🇮🇶" },
    { name: "Syria", flag: "🇸🇾" },
    { name: "Lebanon", flag: "🇱🇧" },
    //allez
    { name: "South Africa", flag: "🇿🇦" },
    { name: "Nigeria", flag: "🇳🇬" },
    { name: "Egypt", flag: "🇪🇬" },
    { name: "Algeria", flag: "🇩🇿" },
    { name: "Morocco", flag: "🇲🇦" },
    { name: "Tunisia", flag: "🇹🇳" },
    { name: "Libya", flag: "🇱🇾" },
    { name: "Sudan", flag: "🇸🇩" },
    { name: "Ethiopia", flag: "🇪🇹" },
    { name: "Kenya", flag: "🇰🇪" },
    { name: "Uganda", flag: "🇺🇬" },
    { name: "Ghana", flag: "🇬🇭" },
    { name: "Cameroon", flag: "🇨🇲" },
    { name: "Ivory Coast", flag: "🇨🇮" },
    { name: "Senegal", flag: "🇸🇳" },
    { name: "Mali", flag: "🇲🇱" },
    { name: "Niger", flag: "🇳🇪" },
    { name: "Chad", flag: "🇹🇩" },
    { name: "Mauritania", flag: "🇲🇷" },
    { name: "Mozambique", flag: "🇲🇿" },
    { name: "Madagascar", flag: "🇲🇬" },
    { name: "Zimbabwe", flag: "🇿🇼" },
    { name: "Zambia", flag: "🇿🇲" },
    { name: "Angola", flag: "🇦🇴" },
    { name: "Namibia", flag: "🇳🇦" },
    { name: "Botswana", flag: "🇧🇼" },
    { name: "Mauritius", flag: "🇲🇺" },
    { name: "Malawi", flag: "🇲🇼" },
    { name: "Lesotho", flag: "🇱🇸" },
    { name: "Swaziland", flag: "🇸🇿" },
    { name: "Burundi", flag: "🇧🇮" },
    { name: "Rwanda", flag: "🇷🇼" },
    //come on for the last time
    { name: "Antarctica", flag: "🇦🇶" },
    { name: "Greenland", flag: "🇬🇱" },
    { name: "Faroe Islands", flag: "🇫🇴" },
    { name: "Iceland", flag: "🇮🇸" },
    { name: "Svalbard and Jan Mayen", flag: "🇸🇯" },
    { name: "United Kingdom", flag: "🇬🇧" },
    { name: "Ireland", flag: "🇮🇪" }
].sort((a, b) => a.name.localeCompare(b.name));
